# Generated by Django 3.1.4 on 2021-02-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brevet_Ar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='رابط')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='المادة')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='الموضوع')),
                ('text', models.TextField()),
                ('create', models.IntegerField(blank=True, null=True, verbose_name='تاريخ مسابقة')),
                ('select_brevet', models.CharField(choices=[('brevet_ar_20', 'بريفة 20'), ('brevet_ar_19', 'بريفة 19'), ('brevet_ar_18', 'بريفة 18'), ('brevet_ar_17', 'بريفة 17'), ('brevet_ar_16', 'بريفة 16'), ('brevet_ar_15', 'بريفة 15')], max_length=20, verbose_name='اختر المسابقة')),
                ('status', models.CharField(choices=[('draft', 'إخفاء'), ('published', 'نشر')], default='draft', max_length=20, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'Brevet_Ar',
                'verbose_name_plural': 'Brevet_Ar',
            },
        ),
        migrations.CreateModel(
            name='Cours_Ar_T',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'c_ar_title',
                'verbose_name_plural': 'c_ar_title',
            },
        ),
        migrations.CreateModel(
            name='Cours_Ar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='رابط')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='العنوان')),
                ('text', models.TextField(verbose_name='المنشور')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ')),
                ('status', models.CharField(choices=[('draft', 'إخفاء'), ('published', 'نشر')], default='draft', max_length=20, verbose_name='الحالة')),
                ('Lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='الدروس', to='coursar.cours_ar_t')),
            ],
            options={
                'verbose_name': 'cours_ar',
                'verbose_name_plural': 'cours_ar',
            },
        ),
    ]
