# Generated by Django 3.1.3 on 2020-12-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bepcar2015',
            options={'verbose_name': 'BEPC_AR_2015', 'verbose_name_plural': 'BEPC_AR_2015'},
        ),
        migrations.AlterModelOptions(
            name='bepcar2016',
            options={'verbose_name': 'BEPC_AR_2016', 'verbose_name_plural': 'BEPC_AR_2016'},
        ),
        migrations.AlterModelOptions(
            name='bepcar2017',
            options={'verbose_name': 'BEPC_AR_2017', 'verbose_name_plural': 'BEPC_AR_2017'},
        ),
        migrations.AlterModelOptions(
            name='bepcar2018',
            options={'verbose_name': 'BEPC_AR_2018', 'verbose_name_plural': 'BEPC_AR_2018'},
        ),
        migrations.AlterModelOptions(
            name='bepcar2019',
            options={'verbose_name': 'BEPC_AR_2019', 'verbose_name_plural': 'BEPC_AR_2019'},
        ),
        migrations.AlterModelOptions(
            name='bepcar2020',
            options={'verbose_name': 'BEPC_AR_2020', 'verbose_name_plural': 'BEPC_AR_2020'},
        ),
        migrations.AlterField(
            model_name='bepcar2020',
            name='create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت النشر'),
        ),
    ]
