# Generated by Django 3.1.3 on 2020-12-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursar', '0002_auto_20201203_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bepcar2020',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='وقت النشر'),
        ),
    ]
