# Generated by Django 3.1.3 on 2020-12-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursar', '0003_auto_20201203_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bepcar2015',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='مسابقة'),
        ),
        migrations.AlterField(
            model_name='bepcar2016',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='مسابقة'),
        ),
        migrations.AlterField(
            model_name='bepcar2017',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='مسابقة'),
        ),
        migrations.AlterField(
            model_name='bepcar2018',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='مسابقة'),
        ),
        migrations.AlterField(
            model_name='bepcar2019',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='مسابقة'),
        ),
        migrations.AlterField(
            model_name='bepcar2020',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='مسابقة'),
        ),
    ]
