# Generated by Django 3.1.4 on 2021-01-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursar', '0005_bepcar2020_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bepcar2020',
            name='is_draft',
        ),
    ]
