# Generated by Django 3.1.4 on 2021-01-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursar', '0006_remove_bepcar2020_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='bepcar2020',
            name='posted',
            field=models.CharField(choices=[('publish', 'نشر'), ('draft', 'اخفاء')], default=1, max_length=50, verbose_name='المنشور'),
            preserve_default=False,
        ),
    ]
