# Generated by Django 3.1.4 on 2021-01-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursar', '0007_bepcar2020_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bepcar2020',
            name='posted',
        ),
        migrations.AddField(
            model_name='bepcar2020',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
