# Generated by Django 3.1.4 on 2021-01-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursar', '0011_auto_20210109_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bepcar2016',
            old_name='create',
            new_name='brevet',
        ),
        migrations.RenameField(
            model_name='bepcar2017',
            old_name='create',
            new_name='brevet',
        ),
        migrations.RenameField(
            model_name='bepcar2018',
            old_name='create',
            new_name='brevet',
        ),
        migrations.RenameField(
            model_name='bepcar2019',
            old_name='create',
            new_name='brevet',
        ),
        migrations.RenameField(
            model_name='bepcar2020',
            old_name='create',
            new_name='brevet',
        ),
        migrations.RemoveField(
            model_name='bepcar2015',
            name='create',
        ),
        migrations.AddField(
            model_name='bepcar2015',
            name='brevet',
            field=models.IntegerField(blank=True, null=True, verbose_name='مسابقة'),
        ),
    ]
