# Generated by Django 3.1.4 on 2021-02-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brevet_Fr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='subject')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Post')),
                ('create', models.IntegerField(blank=True, null=True, verbose_name='brevet date')),
                ('select_brevet', models.CharField(choices=[('brevet_fr_20', 'brevet 20'), ('brevet_fr_19', 'brevet 19'), ('brevet_fr_18', 'brevet 18'), ('brevet_fr_17', 'brevet 17'), ('brevet_fr_16', 'brevet 16'), ('brevet_fr_15', 'brevet 15')], max_length=20, verbose_name='choice brevet')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Brevet_Fr',
                'verbose_name_plural': 'Brevet_Fr',
            },
        ),
        migrations.CreateModel(
            name='Cours_Fr_T',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titel')),
            ],
            options={
                'verbose_name': 'C_Fr_Title',
                'verbose_name_plural': 'C_Fr_Title',
            },
        ),
        migrations.CreateModel(
            name='Cours_Fr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Titel')),
                ('text', models.TextField(verbose_name='Post')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status')),
                ('Lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lesson', to='coursfr.cours_fr_t')),
            ],
            options={
                'verbose_name': 'Cours_Fr',
                'verbose_name_plural': 'Cours_Fr',
            },
        ),
    ]
