# Generated by Django 3.1.4 on 2021-03-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursfr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brevet_fr',
            name='shor',
            field=models.CharField(default=1, max_length=300, verbose_name='short disc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours_fr',
            name='shor',
            field=models.CharField(default=1, max_length=300, verbose_name='short disc'),
            preserve_default=False,
        ),
    ]
