# Generated by Django 3.1.3 on 2020-12-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursfr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bepcfr2015',
            options={'verbose_name': 'BEPC_FR_2015', 'verbose_name_plural': 'BEPC_FR_2015'},
        ),
        migrations.AlterModelOptions(
            name='bepcfr2016',
            options={'verbose_name': 'BEPC_FR_2016', 'verbose_name_plural': 'BEPC_FR_2016'},
        ),
        migrations.AlterModelOptions(
            name='bepcfr2017',
            options={'verbose_name': 'BEPC_FR_2017', 'verbose_name_plural': 'BEPC_FR_2017'},
        ),
        migrations.AlterModelOptions(
            name='bepcfr2018',
            options={'verbose_name': 'BEPC_FR_2018', 'verbose_name_plural': 'BEPC_FR_2018'},
        ),
        migrations.AlterModelOptions(
            name='bepcfr2019',
            options={'verbose_name': 'BEPC_FR_2019', 'verbose_name_plural': 'BEPC_FR_2019'},
        ),
        migrations.AlterModelOptions(
            name='bepcfr2020',
            options={'verbose_name': 'BEPC_FR_2020', 'verbose_name_plural': 'BEPC_FR_2020'},
        ),
    ]
