# Generated by Django 3.1.3 on 2020-12-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursfr', '0002_auto_20201203_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bepcfr2015',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='bepcfr2016',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='bepcfr2017',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='bepcfr2018',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='bepcfr2019',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='bepcfr2020',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='bepcfr2015',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='brevet'),
        ),
        migrations.AlterField(
            model_name='bepcfr2016',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='brevet'),
        ),
        migrations.AlterField(
            model_name='bepcfr2017',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='brevet'),
        ),
        migrations.AlterField(
            model_name='bepcfr2018',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='brevet'),
        ),
        migrations.AlterField(
            model_name='bepcfr2019',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='brevet'),
        ),
        migrations.AlterField(
            model_name='bepcfr2020',
            name='create',
            field=models.DateField(blank=True, null=True, verbose_name='brevet'),
        ),
    ]
