# Generated by Django 3.1.4 on 2021-01-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursfr', '0003_auto_20201203_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='bepcfr2015',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='bepcfr2016',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='bepcfr2017',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='bepcfr2018',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='bepcfr2019',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='bepcfr2020',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
