# Generated by Django 3.1.4 on 2021-01-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursfr', '0004_auto_20210108_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bepcfr2015',
            name='create',
        ),
        migrations.RemoveField(
            model_name='bepcfr2016',
            name='create',
        ),
        migrations.RemoveField(
            model_name='bepcfr2017',
            name='create',
        ),
        migrations.RemoveField(
            model_name='bepcfr2018',
            name='create',
        ),
        migrations.RemoveField(
            model_name='bepcfr2019',
            name='create',
        ),
        migrations.RemoveField(
            model_name='bepcfr2020',
            name='create',
        ),
        migrations.AddField(
            model_name='bepcfr2015',
            name='brevet',
            field=models.IntegerField(blank=True, null=True, verbose_name='brevet'),
        ),
        migrations.AddField(
            model_name='bepcfr2016',
            name='brevet',
            field=models.IntegerField(blank=True, null=True, verbose_name='brevet'),
        ),
        migrations.AddField(
            model_name='bepcfr2017',
            name='brevet',
            field=models.IntegerField(blank=True, null=True, verbose_name='brevet'),
        ),
        migrations.AddField(
            model_name='bepcfr2018',
            name='brevet',
            field=models.IntegerField(blank=True, null=True, verbose_name='brevet'),
        ),
        migrations.AddField(
            model_name='bepcfr2019',
            name='brevet',
            field=models.IntegerField(blank=True, null=True, verbose_name='brevet'),
        ),
        migrations.AddField(
            model_name='bepcfr2020',
            name='brevet',
            field=models.IntegerField(blank=True, null=True, verbose_name='brevet'),
        ),
    ]
